//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Characters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public int id_characters { get; set; }
        public string Name { get; set; }
        public Nullable<int> FK_Weapon { get; set; }
        public Nullable<int> FK_Power { get; set; }
        public Nullable<int> FK_Lvl { get; set; }
        public Nullable<int> FK_Status { get; set; }
        public Nullable<int> FK_Type { get; set; }
    
        public virtual LevelNPC LevelNPC { get; set; }
        public virtual PowerCharacters PowerCharacters { get; set; }
        public virtual StatusCharacters StatusCharacters { get; set; }
        public virtual TypeCharacters TypeCharacters { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
