//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Characters
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameCharactersEntities : DbContext
    {
        private static GameCharactersEntities _context;
        public GameCharactersEntities()
            : base("name=GameCharactersEntities")
        {
        }

        public static GameCharactersEntities GetContext() //метод для обработки поля
        {
            if (_context == null)
                _context = new GameCharactersEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<LevelNPC> LevelNPC { get; set; }
        public virtual DbSet<PowerCharacters> PowerCharacters { get; set; }
        public virtual DbSet<StatusCharacters> StatusCharacters { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeCharacters> TypeCharacters { get; set; }
        public virtual DbSet<TypeWeapon> TypeWeapon { get; set; }
        public virtual DbSet<Weapon> Weapon { get; set; }
    }
}
